# Generated by Django 4.1.3 on 2022-12-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0003_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
