# Generated by Django 4.1.3 on 2022-12-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catitle', models.CharField(max_length=100, verbose_name='Title')),
                ('CaSubTitle', models.CharField(max_length=150, verbose_name='Subtitle')),
                ('CaImage', models.ImageField(upload_to='carouselImage', verbose_name='Image')),
                ('Status', models.BooleanField(default=False)),
                ('offer_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
