# Generated by Django 4.1.3 on 2022-12-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
